<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GraphRoots.GraphDbCli</RootNamespace>
    <AssemblyName>GraphDbCli</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Neo4j.Driver" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GraphDb\GraphDb.csproj" />
    <ProjectReference Include="..\GrasshopperLib\GrasshopperLib.csproj" />
  </ItemGroup>
</Project>
